name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
run:
  working-directory: ./food-waste-tracker
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm install

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Expo Setup
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_BUILD_SECRET}}
          expo-cache: true

      - name: Build on EAS
        run: EAS_BUILD_AUTOCOMMIT=${{1}} npx eas-cli build --platform android --profile development --non-interactive

  # Build IOS job will require apple developer account which costs $99/year
  # build-ios:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install npm dependencies
  #       run: npm install

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 18.x

  #     - name: Expo Setup
  #       uses: expo/expo-github-action@v6
  #       with:
  #         expo-version: 4.x
  #         token: ${{ secrets.EXPO_BUILD_SECRET}}
  #         expo-cache: true

  #     - name: Build on EAS
  #       run: EAS_BUILD_AUTOCOMMIT=${{1}} npx eas-cli build --platform ios --profile development --non-interactive
